CREATE TABLE IF NOT EXISTS chemicals (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  formula VARCHAR(120) NOT NULL DEFAULT '',
  category VARCHAR(120) NOT NULL DEFAULT '',
  unit VARCHAR(40) NOT NULL DEFAULT '',
  quantity NUMERIC(12,2) NOT NULL DEFAULT 0,
  max_quantity NUMERIC(12,2) NOT NULL DEFAULT 0,
  low_stock_quantity NUMERIC(12,2) NOT NULL DEFAULT 0,
  hazard_info VARCHAR(255) NOT NULL,
  room_no VARCHAR(50) NOT NULL,
  expiry_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(40) NOT NULL DEFAULT 'staff',
  reset_code VARCHAR(20),
  reset_expires TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS logs (
  id BIGSERIAL PRIMARY KEY,
  chemical_id BIGINT NOT NULL REFERENCES chemicals(id) ON DELETE CASCADE,
  action VARCHAR(20) NOT NULL CHECK (action IN ('use', 'refill')),
  amount NUMERIC(12,2) NOT NULL,
  date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "user" VARCHAR(120) NOT NULL,
  purpose VARCHAR(160),
  class_name VARCHAR(120)
);
